<?php
/**
 * User: ketu.lai <ketu.lai@gmail.com>
 * Date: 2017/3/6
 */

namespace Veda\Lazada\Tests;

use GuzzleHttp\Psr7\Response;
use PHPUnit\Framework\TestCase;
use Veda\Lazada\Client;
use Veda\Lazada\Response\JsonResponse;
use Veda\Lazada\Response\ResponseAbstract;
use Veda\Lazada\ResponseFactory;

class ResponseFactoryTest extends TestCase
{
    protected $response;
    public function setUp()
    {
        $this->response = new Response();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testCreate()
    {
        $response = ResponseFactory::create(JsonResponse::class, $this->response);
        $this->assertInstanceOf(ResponseAbstract::class, $response);
    }


    /**
     * @expectedException InvalidArgumentException
     */
    public function testHandleNotExists()
    {
        ResponseFactory::create("xxxx", $this->response);
    }
}