<?php
/**
 * User: ketu.lai <ketu.lai@gmail.com>
 * Date: 2017/2/22
 */

namespace Veda\Lazada\Request\Image;

use Veda\Lazada\Exception\InvalidArgumentException;
use Veda\Lazada\Request\RequestAbstract;
use Veda\Lazada\Utils\ArrayToXml;

class Migrate extends RequestAbstract
{
    protected $imageUrl;

    public function getAction()
    {
        return 'MigrateImage';
        // TODO: Implement getAction() method.
    }

    public function getMethod()
    {
        // TODO: Implement getMethod() method.
        return self::HTTP_METHOD_POST;
    }

    public function setImageUrl($url)
    {
        $this->imageUrl = $url;
    }
    protected function getRequestBody()
    {
        if (!$this->imageUrl) {
            throw new InvalidArgumentException('no image url set in the request %s', __CLASS__);
        }
        $data = [
            'Image' => [
                'Url' => $this->imageUrl,
            ]
        ];
        $xml = ArrayToXml::convert($data, 'Request');
        $this->requestBody = $xml;

        return parent::getRequestBody(); // TODO: Change the autogenerated stub
    }
}