<?php
/**
 * User: ketu.lai <ketu.lai@gmail.com>
 * Date: 2017/3/6
 */

namespace Veda\Lazada\Request\Image;

use Veda\Lazada\Exception\InvalidArgumentException;
use Veda\Lazada\Request\RequestAbstract;

class Upload extends RequestAbstract
{
    protected $imageFile;

    public function getAction()
    {
        // TODO: Implement getAction() method.
        return 'UploadImage';
    }

    public function getMethod()
    {
        // TODO: Implement getMethod() method.
        return self::HTTP_METHOD_POST;
    }

    public function setImageFile($file)
    {
        $this->imageFile = $file;
    }

    protected function getRequestBody()
    {
        if (!$this->imageFile) {
            throw new InvalidArgumentException("no file was added to the request %s", __CLASS__);
        }


        if (file_exists($this->imageFile && is_readable($this->imageFile))) {
            throw new InvalidArgumentException("can not add file (%s) to the request %s", [$this->imageFile, __CLASS__]);
        }

        $this->requestBody = fopen($this->imageFile, 'rb');

        return parent::getRequestBody(); // TODO: Change the autogenerated stub
    }
}