<?php
/**
 * User: ketu.lai <ketu.lai@gmail.com>
 * Date: 2017/3/6
 */

namespace Veda\Lazada\Request\Account;

use Veda\Lazada\Request\RequestAbstract;

/**
 * Class Seller
 * @package Veda\Lazada\Request\Account
 * @desc This call will update a seller email address for the seller of the user making the call.
 */
class Seller extends RequestAbstract
{
    protected $email;

    public function getAction()
    {
        // TODO: Implement getAction() method.
        return "SellerUpdate";
    }

    public function getMethod()
    {
        // TODO: Implement getMethod() method.
        return self::HTTP_METHOD_POST;
    }

    public function setEmail($email)
    {
        $this->email = $email;
    }
    protected function getRequestBody()
    {
        $data = [
            'Seller'=>[
                'Email'=> $this->email,
            ]
        ];
        $this->requestBody = ArrayToXml::convert($data, 'Request');

        return parent::getRequestBody(); // TODO: Change the autogenerated stub
    }
}