<?php
/**
 * User: ketu.lai <ketu.lai@gmail.com>
 * Date: 2017/3/6
 */

namespace Veda\Lazada\Request\Account;

use Veda\Lazada\Request\RequestAbstract;
use Veda\Lazada\Utils\ArrayToXml;

/**
 * Class User
 * @package Veda\Lazada\Request\Account
 * @desc This call will update an user email address for the seller of the user making the call.
 */
class User extends RequestAbstract
{
    protected $newEmail;
    protected $oldEmail;

    public function getAction()
    {
        // TODO: Implement getAction() method.
        return "UserUpdate";
    }

    public function getMethod()
    {
        // TODO: Implement getMethod() method.
        return self::HTTP_METHOD_POST;
    }

    public function setNewEmail($newEmail)
    {
        $this->newEmail = $newEmail;
    }

    public function setOldEmail($oldEmail)
    {
        $this->oldEmail = $oldEmail;
    }
    protected function getRequestBody()
    {
        $data = [
            'User'=>[
                'NewEmail'=> $this->newEmail,
                'OldEmail'=> $this->oldEmail,
            ]
        ];
        $this->requestBody = ArrayToXml::convert($data, 'Request');

        return parent::getRequestBody(); // TODO: Change the autogenerated stub
    }
}